buildscript {
  dependencies {
    classpath libs.mavenPublishPlugin
  }
  repositories {
    mavenCentral()
  }
}

apply plugin: 'java-library'
apply plugin: 'com.vanniktech.maven.publish'

repositories {
  mavenCentral()
}

dependencies {
  testImplementation libs.junit
}

sourceSets {
  main.java.srcDir('platform_dalvik/dx/src')
  test.java.srcDir('platform_dalvik/dx/junit-tests')
}

java {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
}

tasks.javadoc {
  options.addStringOption('Xdoclint:none', '-quiet')
}
